/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AcademicAttendanceRouteImport } from './routes/academic.attendance'
import { Route as AcademicClassesRouteImport } from './routes/academic.classes'
import { Route as AcademicExaminationsRouteImport } from './routes/academic.examinations'
import { Route as AcademicReportCardsRouteImport } from './routes/academic.report-cards'
import { Route as AcademicResultsRouteImport } from './routes/academic.results'
import { Route as AcademicSectionsRouteImport } from './routes/academic.sections'
import { Route as AcademicStudentsRouteImport } from './routes/academic.students'
import { Route as AcademicSubjectsRouteImport } from './routes/academic.subjects'
import { Route as AcademicTeachersRouteImport } from './routes/academic.teachers'
import { Route as AcademicTimetableRouteImport } from './routes/academic.timetable'
import { Route as AdministrationCommunicationRouteImport } from './routes/administration.communication'
import { Route as AdministrationDocumentsRouteImport } from './routes/administration.documents'
import { Route as AdministrationEventsRouteImport } from './routes/administration.events'
import { Route as AdministrationInventoryRouteImport } from './routes/administration.inventory'
import { Route as AdministrationLibraryRouteImport } from './routes/administration.library'
import { Route as AdministrationTransportRouteImport } from './routes/administration.transport'
import { Route as AdmissionsApplicationsRouteImport } from './routes/admissions.applications'
import { Route as AdmissionsEnquiriesRouteImport } from './routes/admissions.enquiries'
import { Route as AdmissionsProcessRouteImport } from './routes/admissions.process'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceFeeStructureRouteImport } from './routes/finance.fee-structure'
import { Route as FinanceFeesRouteImport } from './routes/finance.fees'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as HrLeaveManagementRouteImport } from './routes/hr.leave-management'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrStaffRouteImport } from './routes/hr.staff'
import { Route as LearningAssignmentsRouteImport } from './routes/learning.assignments'
import { Route as LearningCoursesRouteImport } from './routes/learning.courses'
import { Route as LearningLessonsRouteImport } from './routes/learning.lessons'
import { Route as LearningOnlineClassesRouteImport } from './routes/learning.online-classes'
import { Route as ReportsAcademicRouteImport } from './routes/reports.academic'
import { Route as ReportsAttendanceRouteImport } from './routes/reports.attendance'
import { Route as ReportsFeesRouteImport } from './routes/reports.fees'
import { Route as ReportsStudentsRouteImport } from './routes/reports.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicAttendanceRoute = AcademicAttendanceRouteImport.update({
  id: '/academic/attendance',
  path: '/academic/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicClassesRoute = AcademicClassesRouteImport.update({
  id: '/academic/classes',
  path: '/academic/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicExaminationsRoute = AcademicExaminationsRouteImport.update({
  id: '/academic/examinations',
  path: '/academic/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicReportCardsRoute = AcademicReportCardsRouteImport.update({
  id: '/academic/report-cards',
  path: '/academic/report-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResultsRoute = AcademicResultsRouteImport.update({
  id: '/academic/results',
  path: '/academic/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSectionsRoute = AcademicSectionsRouteImport.update({
  id: '/academic/sections',
  path: '/academic/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicStudentsRoute = AcademicStudentsRouteImport.update({
  id: '/academic/students',
  path: '/academic/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSubjectsRoute = AcademicSubjectsRouteImport.update({
  id: '/academic/subjects',
  path: '/academic/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicTeachersRoute = AcademicTeachersRouteImport.update({
  id: '/academic/teachers',
  path: '/academic/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicTimetableRoute = AcademicTimetableRouteImport.update({
  id: '/academic/timetable',
  path: '/academic/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationCommunicationRoute =
  AdministrationCommunicationRouteImport.update({
    id: '/administration/communication',
    path: '/administration/communication',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationDocumentsRoute = AdministrationDocumentsRouteImport.update({
  id: '/administration/documents',
  path: '/administration/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationEventsRoute = AdministrationEventsRouteImport.update({
  id: '/administration/events',
  path: '/administration/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationInventoryRoute = AdministrationInventoryRouteImport.update({
  id: '/administration/inventory',
  path: '/administration/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationLibraryRoute = AdministrationLibraryRouteImport.update({
  id: '/administration/library',
  path: '/administration/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationTransportRoute = AdministrationTransportRouteImport.update({
  id: '/administration/transport',
  path: '/administration/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplicationsRoute = AdmissionsApplicationsRouteImport.update({
  id: '/admissions/applications',
  path: '/admissions/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsEnquiriesRoute = AdmissionsEnquiriesRouteImport.update({
  id: '/admissions/enquiries',
  path: '/admissions/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsProcessRoute = AdmissionsProcessRouteImport.update({
  id: '/admissions/process',
  path: '/admissions/process',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFeeStructureRoute = FinanceFeeStructureRouteImport.update({
  id: '/finance/fee-structure',
  path: '/finance/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFeesRoute = FinanceFeesRouteImport.update({
  id: '/finance/fees',
  path: '/finance/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveManagementRoute = HrLeaveManagementRouteImport.update({
  id: '/hr/leave-management',
  path: '/hr/leave-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrStaffRoute = HrStaffRouteImport.update({
  id: '/hr/staff',
  path: '/hr/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningAssignmentsRoute = LearningAssignmentsRouteImport.update({
  id: '/learning/assignments',
  path: '/learning/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCoursesRoute = LearningCoursesRouteImport.update({
  id: '/learning/courses',
  path: '/learning/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningLessonsRoute = LearningLessonsRouteImport.update({
  id: '/learning/lessons',
  path: '/learning/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningOnlineClassesRoute = LearningOnlineClassesRouteImport.update({
  id: '/learning/online-classes',
  path: '/learning/online-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAcademicRoute = ReportsAcademicRouteImport.update({
  id: '/reports/academic',
  path: '/reports/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAttendanceRoute = ReportsAttendanceRouteImport.update({
  id: '/reports/attendance',
  path: '/reports/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFeesRoute = ReportsFeesRouteImport.update({
  id: '/reports/fees',
  path: '/reports/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStudentsRoute = ReportsStudentsRouteImport.update({
  id: '/reports/students',
  path: '/reports/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/applications'
    | '/admissions/enquiries'
    | '/admissions/process'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/applications'
    | '/admissions/enquiries'
    | '/admissions/process'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/applications'
    | '/admissions/enquiries'
    | '/admissions/process'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  AcademicAttendanceRoute: typeof AcademicAttendanceRoute
  AcademicClassesRoute: typeof AcademicClassesRoute
  AcademicExaminationsRoute: typeof AcademicExaminationsRoute
  AcademicReportCardsRoute: typeof AcademicReportCardsRoute
  AcademicResultsRoute: typeof AcademicResultsRoute
  AcademicSectionsRoute: typeof AcademicSectionsRoute
  AcademicStudentsRoute: typeof AcademicStudentsRoute
  AcademicSubjectsRoute: typeof AcademicSubjectsRoute
  AcademicTeachersRoute: typeof AcademicTeachersRoute
  AcademicTimetableRoute: typeof AcademicTimetableRoute
  AdministrationCommunicationRoute: typeof AdministrationCommunicationRoute
  AdministrationDocumentsRoute: typeof AdministrationDocumentsRoute
  AdministrationEventsRoute: typeof AdministrationEventsRoute
  AdministrationInventoryRoute: typeof AdministrationInventoryRoute
  AdministrationLibraryRoute: typeof AdministrationLibraryRoute
  AdministrationTransportRoute: typeof AdministrationTransportRoute
  AdmissionsApplicationsRoute: typeof AdmissionsApplicationsRoute
  AdmissionsEnquiriesRoute: typeof AdmissionsEnquiriesRoute
  AdmissionsProcessRoute: typeof AdmissionsProcessRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceFeeStructureRoute: typeof FinanceFeeStructureRoute
  FinanceFeesRoute: typeof FinanceFeesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  HrLeaveManagementRoute: typeof HrLeaveManagementRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrStaffRoute: typeof HrStaffRoute
  LearningAssignmentsRoute: typeof LearningAssignmentsRoute
  LearningCoursesRoute: typeof LearningCoursesRoute
  LearningLessonsRoute: typeof LearningLessonsRoute
  LearningOnlineClassesRoute: typeof LearningOnlineClassesRoute
  ReportsAcademicRoute: typeof ReportsAcademicRoute
  ReportsAttendanceRoute: typeof ReportsAttendanceRoute
  ReportsFeesRoute: typeof ReportsFeesRoute
  ReportsStudentsRoute: typeof ReportsStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/attendance': {
      id: '/academic/attendance'
      path: '/academic/attendance'
      fullPath: '/academic/attendance'
      preLoaderRoute: typeof AcademicAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/classes': {
      id: '/academic/classes'
      path: '/academic/classes'
      fullPath: '/academic/classes'
      preLoaderRoute: typeof AcademicClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/examinations': {
      id: '/academic/examinations'
      path: '/academic/examinations'
      fullPath: '/academic/examinations'
      preLoaderRoute: typeof AcademicExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/report-cards': {
      id: '/academic/report-cards'
      path: '/academic/report-cards'
      fullPath: '/academic/report-cards'
      preLoaderRoute: typeof AcademicReportCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/results': {
      id: '/academic/results'
      path: '/academic/results'
      fullPath: '/academic/results'
      preLoaderRoute: typeof AcademicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/sections': {
      id: '/academic/sections'
      path: '/academic/sections'
      fullPath: '/academic/sections'
      preLoaderRoute: typeof AcademicSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/students': {
      id: '/academic/students'
      path: '/academic/students'
      fullPath: '/academic/students'
      preLoaderRoute: typeof AcademicStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/subjects': {
      id: '/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AcademicSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/teachers': {
      id: '/academic/teachers'
      path: '/academic/teachers'
      fullPath: '/academic/teachers'
      preLoaderRoute: typeof AcademicTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/timetable': {
      id: '/academic/timetable'
      path: '/academic/timetable'
      fullPath: '/academic/timetable'
      preLoaderRoute: typeof AcademicTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/communication': {
      id: '/administration/communication'
      path: '/administration/communication'
      fullPath: '/administration/communication'
      preLoaderRoute: typeof AdministrationCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/documents': {
      id: '/administration/documents'
      path: '/administration/documents'
      fullPath: '/administration/documents'
      preLoaderRoute: typeof AdministrationDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/events': {
      id: '/administration/events'
      path: '/administration/events'
      fullPath: '/administration/events'
      preLoaderRoute: typeof AdministrationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/inventory': {
      id: '/administration/inventory'
      path: '/administration/inventory'
      fullPath: '/administration/inventory'
      preLoaderRoute: typeof AdministrationInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/library': {
      id: '/administration/library'
      path: '/administration/library'
      fullPath: '/administration/library'
      preLoaderRoute: typeof AdministrationLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/transport': {
      id: '/administration/transport'
      path: '/administration/transport'
      fullPath: '/administration/transport'
      preLoaderRoute: typeof AdministrationTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications': {
      id: '/admissions/applications'
      path: '/admissions/applications'
      fullPath: '/admissions/applications'
      preLoaderRoute: typeof AdmissionsApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries': {
      id: '/admissions/enquiries'
      path: '/admissions/enquiries'
      fullPath: '/admissions/enquiries'
      preLoaderRoute: typeof AdmissionsEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/process': {
      id: '/admissions/process'
      path: '/admissions/process'
      fullPath: '/admissions/process'
      preLoaderRoute: typeof AdmissionsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fee-structure': {
      id: '/finance/fee-structure'
      path: '/finance/fee-structure'
      fullPath: '/finance/fee-structure'
      preLoaderRoute: typeof FinanceFeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fees': {
      id: '/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof FinanceFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave-management': {
      id: '/hr/leave-management'
      path: '/hr/leave-management'
      fullPath: '/hr/leave-management'
      preLoaderRoute: typeof HrLeaveManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/staff': {
      id: '/hr/staff'
      path: '/hr/staff'
      fullPath: '/hr/staff'
      preLoaderRoute: typeof HrStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/assignments': {
      id: '/learning/assignments'
      path: '/learning/assignments'
      fullPath: '/learning/assignments'
      preLoaderRoute: typeof LearningAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/courses': {
      id: '/learning/courses'
      path: '/learning/courses'
      fullPath: '/learning/courses'
      preLoaderRoute: typeof LearningCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/lessons': {
      id: '/learning/lessons'
      path: '/learning/lessons'
      fullPath: '/learning/lessons'
      preLoaderRoute: typeof LearningLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/online-classes': {
      id: '/learning/online-classes'
      path: '/learning/online-classes'
      fullPath: '/learning/online-classes'
      preLoaderRoute: typeof LearningOnlineClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/academic': {
      id: '/reports/academic'
      path: '/reports/academic'
      fullPath: '/reports/academic'
      preLoaderRoute: typeof ReportsAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance': {
      id: '/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof ReportsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/fees': {
      id: '/reports/fees'
      path: '/reports/fees'
      fullPath: '/reports/fees'
      preLoaderRoute: typeof ReportsFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/students': {
      id: '/reports/students'
      path: '/reports/students'
      fullPath: '/reports/students'
      preLoaderRoute: typeof ReportsStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  AcademicAttendanceRoute: AcademicAttendanceRoute,
  AcademicClassesRoute: AcademicClassesRoute,
  AcademicExaminationsRoute: AcademicExaminationsRoute,
  AcademicReportCardsRoute: AcademicReportCardsRoute,
  AcademicResultsRoute: AcademicResultsRoute,
  AcademicSectionsRoute: AcademicSectionsRoute,
  AcademicStudentsRoute: AcademicStudentsRoute,
  AcademicSubjectsRoute: AcademicSubjectsRoute,
  AcademicTeachersRoute: AcademicTeachersRoute,
  AcademicTimetableRoute: AcademicTimetableRoute,
  AdministrationCommunicationRoute: AdministrationCommunicationRoute,
  AdministrationDocumentsRoute: AdministrationDocumentsRoute,
  AdministrationEventsRoute: AdministrationEventsRoute,
  AdministrationInventoryRoute: AdministrationInventoryRoute,
  AdministrationLibraryRoute: AdministrationLibraryRoute,
  AdministrationTransportRoute: AdministrationTransportRoute,
  AdmissionsApplicationsRoute: AdmissionsApplicationsRoute,
  AdmissionsEnquiriesRoute: AdmissionsEnquiriesRoute,
  AdmissionsProcessRoute: AdmissionsProcessRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceFeeStructureRoute: FinanceFeeStructureRoute,
  FinanceFeesRoute: FinanceFeesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  HrLeaveManagementRoute: HrLeaveManagementRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrStaffRoute: HrStaffRoute,
  LearningAssignmentsRoute: LearningAssignmentsRoute,
  LearningCoursesRoute: LearningCoursesRoute,
  LearningLessonsRoute: LearningLessonsRoute,
  LearningOnlineClassesRoute: LearningOnlineClassesRoute,
  ReportsAcademicRoute: ReportsAcademicRoute,
  ReportsAttendanceRoute: ReportsAttendanceRoute,
  ReportsFeesRoute: ReportsFeesRoute,
  ReportsStudentsRoute: ReportsStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
