/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AcademicAttendanceRouteImport } from './routes/academic.attendance'
import { Route as AcademicClassAllocationReportRouteImport } from './routes/academic.class-allocation-report'
import { Route as AcademicClassesRouteImport } from './routes/academic.classes'
import { Route as AcademicExaminationsRouteImport } from './routes/academic.examinations'
import { Route as AcademicFeedbackReportRouteImport } from './routes/academic.feedback-report'
import { Route as AcademicMarksCardRouteImport } from './routes/academic.marks-card'
import { Route as AcademicMarksReportRouteImport } from './routes/academic.marks-report'
import { Route as AcademicReportCardsRouteImport } from './routes/academic.report-cards'
import { Route as AcademicResultsRouteImport } from './routes/academic.results'
import { Route as AcademicSectionsRouteImport } from './routes/academic.sections'
import { Route as AcademicSmsReportRouteImport } from './routes/academic.sms-report'
import { Route as AcademicStudentTcRouteImport } from './routes/academic.student-tc'
import { Route as AcademicStudentsRouteImport } from './routes/academic.students'
import { Route as AcademicSubjectsRouteImport } from './routes/academic.subjects'
import { Route as AcademicSummatativeReportRouteImport } from './routes/academic.summatative-report'
import { Route as AcademicTeachersRouteImport } from './routes/academic.teachers'
import { Route as AcademicTimetableRouteImport } from './routes/academic.timetable'
import { Route as AcademicWithheldListRouteImport } from './routes/academic.withheld-list'
import { Route as AdministrationCommunicationRouteImport } from './routes/administration.communication'
import { Route as AdministrationDocumentsRouteImport } from './routes/administration.documents'
import { Route as AdministrationEventsRouteImport } from './routes/administration.events'
import { Route as AdministrationInventoryRouteImport } from './routes/administration.inventory'
import { Route as AdministrationLibraryRouteImport } from './routes/administration.library'
import { Route as AdministrationTransportRouteImport } from './routes/administration.transport'
import { Route as AdmissionsAdmittedRouteImport } from './routes/admissions.admitted'
import { Route as AdmissionsApplicationsRouteImport } from './routes/admissions.applications'
import { Route as AdmissionsAppliedRouteImport } from './routes/admissions.applied'
import { Route as AdmissionsEnquiriesRouteImport } from './routes/admissions.enquiries'
import { Route as AdmissionsPortalRouteImport } from './routes/admissions.portal'
import { Route as AdmissionsProcessRouteImport } from './routes/admissions.process'
import { Route as AdmissionsRegistrationRouteImport } from './routes/admissions.registration'
import { Route as AdmissionsReportRouteImport } from './routes/admissions.report'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceFeeStructureRouteImport } from './routes/finance.fee-structure'
import { Route as FinanceFeesRouteImport } from './routes/finance.fees'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FmsBankRouteImport } from './routes/fms.bank'
import { Route as FmsCancelledFeeListRouteImport } from './routes/fms.cancelled-fee-list'
import { Route as FmsChangeStudentFeeRouteImport } from './routes/fms.change-student-fee'
import { Route as FmsChequeClearenceRouteImport } from './routes/fms.cheque-clearence'
import { Route as FmsDailyMopReportRouteImport } from './routes/fms.daily-mop-report'
import { Route as FmsDayBookReportRouteImport } from './routes/fms.day-book-report'
import { Route as FmsFeeConcessionReportRouteImport } from './routes/fms.fee-concession-report'
import { Route as FmsFeeDescriptionRouteImport } from './routes/fms.fee-description'
import { Route as FmsFeeDescriptionPendingReportRouteImport } from './routes/fms.fee-description-pending-report'
import { Route as FmsFeeDueListPendingReportRouteImport } from './routes/fms.fee-due-list-pending-report'
import { Route as FmsFeeMasterRouteImport } from './routes/fms.fee-master'
import { Route as FmsFeePendingReportRouteImport } from './routes/fms.fee-pending-report'
import { Route as FmsFeePrintListRouteImport } from './routes/fms.fee-print-list'
import { Route as FmsFeeReceiptRouteImport } from './routes/fms.fee-receipt'
import { Route as FmsFeeTypeMasterRouteImport } from './routes/fms.fee-type-master'
import { Route as FmsMopReportRouteImport } from './routes/fms.mop-report'
import { Route as FmsPickupPointRouteImport } from './routes/fms.pickup-point'
import { Route as FmsRteReportRouteImport } from './routes/fms.rte-report'
import { Route as FmsStudentConcessionRouteImport } from './routes/fms.student-concession'
import { Route as FmsTransportFeeDueListPendingReportRouteImport } from './routes/fms.transport-fee-due-list-pending-report'
import { Route as FmsUpdateMaterialFeeRouteImport } from './routes/fms.update-material-fee'
import { Route as FmsUpdateStudentFeeRouteImport } from './routes/fms.update-student-fee'
import { Route as HrLeaveManagementRouteImport } from './routes/hr.leave-management'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrStaffRouteImport } from './routes/hr.staff'
import { Route as LearningAssignmentsRouteImport } from './routes/learning.assignments'
import { Route as LearningCoursesRouteImport } from './routes/learning.courses'
import { Route as LearningLessonsRouteImport } from './routes/learning.lessons'
import { Route as LearningOnlineClassesRouteImport } from './routes/learning.online-classes'
import { Route as ReportsAcademicRouteImport } from './routes/reports.academic'
import { Route as ReportsAttendanceRouteImport } from './routes/reports.attendance'
import { Route as ReportsFeesRouteImport } from './routes/reports.fees'
import { Route as ReportsStudentsRouteImport } from './routes/reports.students'
import { Route as AdmissionsRegistrationStudentIdRouteImport } from './routes/admissions.registration.$studentId'
import { Route as AdmissionsRegistrationNewRouteImport } from './routes/admissions.registration.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicAttendanceRoute = AcademicAttendanceRouteImport.update({
  id: '/academic/attendance',
  path: '/academic/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicClassAllocationReportRoute =
  AcademicClassAllocationReportRouteImport.update({
    id: '/academic/class-allocation-report',
    path: '/academic/class-allocation-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicClassesRoute = AcademicClassesRouteImport.update({
  id: '/academic/classes',
  path: '/academic/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicExaminationsRoute = AcademicExaminationsRouteImport.update({
  id: '/academic/examinations',
  path: '/academic/examinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicFeedbackReportRoute = AcademicFeedbackReportRouteImport.update({
  id: '/academic/feedback-report',
  path: '/academic/feedback-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicMarksCardRoute = AcademicMarksCardRouteImport.update({
  id: '/academic/marks-card',
  path: '/academic/marks-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicMarksReportRoute = AcademicMarksReportRouteImport.update({
  id: '/academic/marks-report',
  path: '/academic/marks-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicReportCardsRoute = AcademicReportCardsRouteImport.update({
  id: '/academic/report-cards',
  path: '/academic/report-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResultsRoute = AcademicResultsRouteImport.update({
  id: '/academic/results',
  path: '/academic/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSectionsRoute = AcademicSectionsRouteImport.update({
  id: '/academic/sections',
  path: '/academic/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSmsReportRoute = AcademicSmsReportRouteImport.update({
  id: '/academic/sms-report',
  path: '/academic/sms-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicStudentTcRoute = AcademicStudentTcRouteImport.update({
  id: '/academic/student-tc',
  path: '/academic/student-tc',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicStudentsRoute = AcademicStudentsRouteImport.update({
  id: '/academic/students',
  path: '/academic/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSubjectsRoute = AcademicSubjectsRouteImport.update({
  id: '/academic/subjects',
  path: '/academic/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSummatativeReportRoute =
  AcademicSummatativeReportRouteImport.update({
    id: '/academic/summatative-report',
    path: '/academic/summatative-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicTeachersRoute = AcademicTeachersRouteImport.update({
  id: '/academic/teachers',
  path: '/academic/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicTimetableRoute = AcademicTimetableRouteImport.update({
  id: '/academic/timetable',
  path: '/academic/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicWithheldListRoute = AcademicWithheldListRouteImport.update({
  id: '/academic/withheld-list',
  path: '/academic/withheld-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationCommunicationRoute =
  AdministrationCommunicationRouteImport.update({
    id: '/administration/communication',
    path: '/administration/communication',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationDocumentsRoute = AdministrationDocumentsRouteImport.update({
  id: '/administration/documents',
  path: '/administration/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationEventsRoute = AdministrationEventsRouteImport.update({
  id: '/administration/events',
  path: '/administration/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationInventoryRoute = AdministrationInventoryRouteImport.update({
  id: '/administration/inventory',
  path: '/administration/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationLibraryRoute = AdministrationLibraryRouteImport.update({
  id: '/administration/library',
  path: '/administration/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationTransportRoute = AdministrationTransportRouteImport.update({
  id: '/administration/transport',
  path: '/administration/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAdmittedRoute = AdmissionsAdmittedRouteImport.update({
  id: '/admissions/admitted',
  path: '/admissions/admitted',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplicationsRoute = AdmissionsApplicationsRouteImport.update({
  id: '/admissions/applications',
  path: '/admissions/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsAppliedRoute = AdmissionsAppliedRouteImport.update({
  id: '/admissions/applied',
  path: '/admissions/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsEnquiriesRoute = AdmissionsEnquiriesRouteImport.update({
  id: '/admissions/enquiries',
  path: '/admissions/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsPortalRoute = AdmissionsPortalRouteImport.update({
  id: '/admissions/portal',
  path: '/admissions/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsProcessRoute = AdmissionsProcessRouteImport.update({
  id: '/admissions/process',
  path: '/admissions/process',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRegistrationRoute = AdmissionsRegistrationRouteImport.update({
  id: '/admissions/registration',
  path: '/admissions/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsReportRoute = AdmissionsReportRouteImport.update({
  id: '/admissions/report',
  path: '/admissions/report',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFeeStructureRoute = FinanceFeeStructureRouteImport.update({
  id: '/finance/fee-structure',
  path: '/finance/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFeesRoute = FinanceFeesRouteImport.update({
  id: '/finance/fees',
  path: '/finance/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsBankRoute = FmsBankRouteImport.update({
  id: '/fms/bank',
  path: '/fms/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsCancelledFeeListRoute = FmsCancelledFeeListRouteImport.update({
  id: '/fms/cancelled-fee-list',
  path: '/fms/cancelled-fee-list',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsChangeStudentFeeRoute = FmsChangeStudentFeeRouteImport.update({
  id: '/fms/change-student-fee',
  path: '/fms/change-student-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsChequeClearenceRoute = FmsChequeClearenceRouteImport.update({
  id: '/fms/cheque-clearence',
  path: '/fms/cheque-clearence',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsDailyMopReportRoute = FmsDailyMopReportRouteImport.update({
  id: '/fms/daily-mop-report',
  path: '/fms/daily-mop-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsDayBookReportRoute = FmsDayBookReportRouteImport.update({
  id: '/fms/day-book-report',
  path: '/fms/day-book-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeeConcessionReportRoute = FmsFeeConcessionReportRouteImport.update({
  id: '/fms/fee-concession-report',
  path: '/fms/fee-concession-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeeDescriptionRoute = FmsFeeDescriptionRouteImport.update({
  id: '/fms/fee-description',
  path: '/fms/fee-description',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeeDescriptionPendingReportRoute =
  FmsFeeDescriptionPendingReportRouteImport.update({
    id: '/fms/fee-description-pending-report',
    path: '/fms/fee-description-pending-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const FmsFeeDueListPendingReportRoute =
  FmsFeeDueListPendingReportRouteImport.update({
    id: '/fms/fee-due-list-pending-report',
    path: '/fms/fee-due-list-pending-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const FmsFeeMasterRoute = FmsFeeMasterRouteImport.update({
  id: '/fms/fee-master',
  path: '/fms/fee-master',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeePendingReportRoute = FmsFeePendingReportRouteImport.update({
  id: '/fms/fee-pending-report',
  path: '/fms/fee-pending-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeePrintListRoute = FmsFeePrintListRouteImport.update({
  id: '/fms/fee-print-list',
  path: '/fms/fee-print-list',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeeReceiptRoute = FmsFeeReceiptRouteImport.update({
  id: '/fms/fee-receipt',
  path: '/fms/fee-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsFeeTypeMasterRoute = FmsFeeTypeMasterRouteImport.update({
  id: '/fms/fee-type-master',
  path: '/fms/fee-type-master',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsMopReportRoute = FmsMopReportRouteImport.update({
  id: '/fms/mop-report',
  path: '/fms/mop-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsPickupPointRoute = FmsPickupPointRouteImport.update({
  id: '/fms/pickup-point',
  path: '/fms/pickup-point',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsRteReportRoute = FmsRteReportRouteImport.update({
  id: '/fms/rte-report',
  path: '/fms/rte-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsStudentConcessionRoute = FmsStudentConcessionRouteImport.update({
  id: '/fms/student-concession',
  path: '/fms/student-concession',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsTransportFeeDueListPendingReportRoute =
  FmsTransportFeeDueListPendingReportRouteImport.update({
    id: '/fms/transport-fee-due-list-pending-report',
    path: '/fms/transport-fee-due-list-pending-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const FmsUpdateMaterialFeeRoute = FmsUpdateMaterialFeeRouteImport.update({
  id: '/fms/update-material-fee',
  path: '/fms/update-material-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const FmsUpdateStudentFeeRoute = FmsUpdateStudentFeeRouteImport.update({
  id: '/fms/update-student-fee',
  path: '/fms/update-student-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveManagementRoute = HrLeaveManagementRouteImport.update({
  id: '/hr/leave-management',
  path: '/hr/leave-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrStaffRoute = HrStaffRouteImport.update({
  id: '/hr/staff',
  path: '/hr/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningAssignmentsRoute = LearningAssignmentsRouteImport.update({
  id: '/learning/assignments',
  path: '/learning/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCoursesRoute = LearningCoursesRouteImport.update({
  id: '/learning/courses',
  path: '/learning/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningLessonsRoute = LearningLessonsRouteImport.update({
  id: '/learning/lessons',
  path: '/learning/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningOnlineClassesRoute = LearningOnlineClassesRouteImport.update({
  id: '/learning/online-classes',
  path: '/learning/online-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAcademicRoute = ReportsAcademicRouteImport.update({
  id: '/reports/academic',
  path: '/reports/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAttendanceRoute = ReportsAttendanceRouteImport.update({
  id: '/reports/attendance',
  path: '/reports/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFeesRoute = ReportsFeesRouteImport.update({
  id: '/reports/fees',
  path: '/reports/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStudentsRoute = ReportsStudentsRouteImport.update({
  id: '/reports/students',
  path: '/reports/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRegistrationStudentIdRoute =
  AdmissionsRegistrationStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AdmissionsRegistrationRoute,
  } as any)
const AdmissionsRegistrationNewRoute =
  AdmissionsRegistrationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdmissionsRegistrationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/class-allocation-report': typeof AcademicClassAllocationReportRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/feedback-report': typeof AcademicFeedbackReportRoute
  '/academic/marks-card': typeof AcademicMarksCardRoute
  '/academic/marks-report': typeof AcademicMarksReportRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/sms-report': typeof AcademicSmsReportRoute
  '/academic/student-tc': typeof AcademicStudentTcRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/summatative-report': typeof AcademicSummatativeReportRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/academic/withheld-list': typeof AcademicWithheldListRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/admitted': typeof AdmissionsAdmittedRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/applied': typeof AdmissionsAppliedRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/admissions/registration': typeof AdmissionsRegistrationRouteWithChildren
  '/admissions/report': typeof AdmissionsReportRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/fms/bank': typeof FmsBankRoute
  '/fms/cancelled-fee-list': typeof FmsCancelledFeeListRoute
  '/fms/change-student-fee': typeof FmsChangeStudentFeeRoute
  '/fms/cheque-clearence': typeof FmsChequeClearenceRoute
  '/fms/daily-mop-report': typeof FmsDailyMopReportRoute
  '/fms/day-book-report': typeof FmsDayBookReportRoute
  '/fms/fee-concession-report': typeof FmsFeeConcessionReportRoute
  '/fms/fee-description': typeof FmsFeeDescriptionRoute
  '/fms/fee-description-pending-report': typeof FmsFeeDescriptionPendingReportRoute
  '/fms/fee-due-list-pending-report': typeof FmsFeeDueListPendingReportRoute
  '/fms/fee-master': typeof FmsFeeMasterRoute
  '/fms/fee-pending-report': typeof FmsFeePendingReportRoute
  '/fms/fee-print-list': typeof FmsFeePrintListRoute
  '/fms/fee-receipt': typeof FmsFeeReceiptRoute
  '/fms/fee-type-master': typeof FmsFeeTypeMasterRoute
  '/fms/mop-report': typeof FmsMopReportRoute
  '/fms/pickup-point': typeof FmsPickupPointRoute
  '/fms/rte-report': typeof FmsRteReportRoute
  '/fms/student-concession': typeof FmsStudentConcessionRoute
  '/fms/transport-fee-due-list-pending-report': typeof FmsTransportFeeDueListPendingReportRoute
  '/fms/update-material-fee': typeof FmsUpdateMaterialFeeRoute
  '/fms/update-student-fee': typeof FmsUpdateStudentFeeRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
  '/admissions/registration/$studentId': typeof AdmissionsRegistrationStudentIdRoute
  '/admissions/registration/new': typeof AdmissionsRegistrationNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/class-allocation-report': typeof AcademicClassAllocationReportRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/feedback-report': typeof AcademicFeedbackReportRoute
  '/academic/marks-card': typeof AcademicMarksCardRoute
  '/academic/marks-report': typeof AcademicMarksReportRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/sms-report': typeof AcademicSmsReportRoute
  '/academic/student-tc': typeof AcademicStudentTcRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/summatative-report': typeof AcademicSummatativeReportRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/academic/withheld-list': typeof AcademicWithheldListRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/admitted': typeof AdmissionsAdmittedRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/applied': typeof AdmissionsAppliedRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/admissions/registration': typeof AdmissionsRegistrationRouteWithChildren
  '/admissions/report': typeof AdmissionsReportRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/fms/bank': typeof FmsBankRoute
  '/fms/cancelled-fee-list': typeof FmsCancelledFeeListRoute
  '/fms/change-student-fee': typeof FmsChangeStudentFeeRoute
  '/fms/cheque-clearence': typeof FmsChequeClearenceRoute
  '/fms/daily-mop-report': typeof FmsDailyMopReportRoute
  '/fms/day-book-report': typeof FmsDayBookReportRoute
  '/fms/fee-concession-report': typeof FmsFeeConcessionReportRoute
  '/fms/fee-description': typeof FmsFeeDescriptionRoute
  '/fms/fee-description-pending-report': typeof FmsFeeDescriptionPendingReportRoute
  '/fms/fee-due-list-pending-report': typeof FmsFeeDueListPendingReportRoute
  '/fms/fee-master': typeof FmsFeeMasterRoute
  '/fms/fee-pending-report': typeof FmsFeePendingReportRoute
  '/fms/fee-print-list': typeof FmsFeePrintListRoute
  '/fms/fee-receipt': typeof FmsFeeReceiptRoute
  '/fms/fee-type-master': typeof FmsFeeTypeMasterRoute
  '/fms/mop-report': typeof FmsMopReportRoute
  '/fms/pickup-point': typeof FmsPickupPointRoute
  '/fms/rte-report': typeof FmsRteReportRoute
  '/fms/student-concession': typeof FmsStudentConcessionRoute
  '/fms/transport-fee-due-list-pending-report': typeof FmsTransportFeeDueListPendingReportRoute
  '/fms/update-material-fee': typeof FmsUpdateMaterialFeeRoute
  '/fms/update-student-fee': typeof FmsUpdateStudentFeeRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
  '/admissions/registration/$studentId': typeof AdmissionsRegistrationStudentIdRoute
  '/admissions/registration/new': typeof AdmissionsRegistrationNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/academic/attendance': typeof AcademicAttendanceRoute
  '/academic/class-allocation-report': typeof AcademicClassAllocationReportRoute
  '/academic/classes': typeof AcademicClassesRoute
  '/academic/examinations': typeof AcademicExaminationsRoute
  '/academic/feedback-report': typeof AcademicFeedbackReportRoute
  '/academic/marks-card': typeof AcademicMarksCardRoute
  '/academic/marks-report': typeof AcademicMarksReportRoute
  '/academic/report-cards': typeof AcademicReportCardsRoute
  '/academic/results': typeof AcademicResultsRoute
  '/academic/sections': typeof AcademicSectionsRoute
  '/academic/sms-report': typeof AcademicSmsReportRoute
  '/academic/student-tc': typeof AcademicStudentTcRoute
  '/academic/students': typeof AcademicStudentsRoute
  '/academic/subjects': typeof AcademicSubjectsRoute
  '/academic/summatative-report': typeof AcademicSummatativeReportRoute
  '/academic/teachers': typeof AcademicTeachersRoute
  '/academic/timetable': typeof AcademicTimetableRoute
  '/academic/withheld-list': typeof AcademicWithheldListRoute
  '/administration/communication': typeof AdministrationCommunicationRoute
  '/administration/documents': typeof AdministrationDocumentsRoute
  '/administration/events': typeof AdministrationEventsRoute
  '/administration/inventory': typeof AdministrationInventoryRoute
  '/administration/library': typeof AdministrationLibraryRoute
  '/administration/transport': typeof AdministrationTransportRoute
  '/admissions/admitted': typeof AdmissionsAdmittedRoute
  '/admissions/applications': typeof AdmissionsApplicationsRoute
  '/admissions/applied': typeof AdmissionsAppliedRoute
  '/admissions/enquiries': typeof AdmissionsEnquiriesRoute
  '/admissions/portal': typeof AdmissionsPortalRoute
  '/admissions/process': typeof AdmissionsProcessRoute
  '/admissions/registration': typeof AdmissionsRegistrationRouteWithChildren
  '/admissions/report': typeof AdmissionsReportRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/fee-structure': typeof FinanceFeeStructureRoute
  '/finance/fees': typeof FinanceFeesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/fms/bank': typeof FmsBankRoute
  '/fms/cancelled-fee-list': typeof FmsCancelledFeeListRoute
  '/fms/change-student-fee': typeof FmsChangeStudentFeeRoute
  '/fms/cheque-clearence': typeof FmsChequeClearenceRoute
  '/fms/daily-mop-report': typeof FmsDailyMopReportRoute
  '/fms/day-book-report': typeof FmsDayBookReportRoute
  '/fms/fee-concession-report': typeof FmsFeeConcessionReportRoute
  '/fms/fee-description': typeof FmsFeeDescriptionRoute
  '/fms/fee-description-pending-report': typeof FmsFeeDescriptionPendingReportRoute
  '/fms/fee-due-list-pending-report': typeof FmsFeeDueListPendingReportRoute
  '/fms/fee-master': typeof FmsFeeMasterRoute
  '/fms/fee-pending-report': typeof FmsFeePendingReportRoute
  '/fms/fee-print-list': typeof FmsFeePrintListRoute
  '/fms/fee-receipt': typeof FmsFeeReceiptRoute
  '/fms/fee-type-master': typeof FmsFeeTypeMasterRoute
  '/fms/mop-report': typeof FmsMopReportRoute
  '/fms/pickup-point': typeof FmsPickupPointRoute
  '/fms/rte-report': typeof FmsRteReportRoute
  '/fms/student-concession': typeof FmsStudentConcessionRoute
  '/fms/transport-fee-due-list-pending-report': typeof FmsTransportFeeDueListPendingReportRoute
  '/fms/update-material-fee': typeof FmsUpdateMaterialFeeRoute
  '/fms/update-student-fee': typeof FmsUpdateStudentFeeRoute
  '/hr/leave-management': typeof HrLeaveManagementRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/staff': typeof HrStaffRoute
  '/learning/assignments': typeof LearningAssignmentsRoute
  '/learning/courses': typeof LearningCoursesRoute
  '/learning/lessons': typeof LearningLessonsRoute
  '/learning/online-classes': typeof LearningOnlineClassesRoute
  '/reports/academic': typeof ReportsAcademicRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fees': typeof ReportsFeesRoute
  '/reports/students': typeof ReportsStudentsRoute
  '/admissions/registration/$studentId': typeof AdmissionsRegistrationStudentIdRoute
  '/admissions/registration/new': typeof AdmissionsRegistrationNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/class-allocation-report'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/feedback-report'
    | '/academic/marks-card'
    | '/academic/marks-report'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/sms-report'
    | '/academic/student-tc'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/summatative-report'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/academic/withheld-list'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/admitted'
    | '/admissions/applications'
    | '/admissions/applied'
    | '/admissions/enquiries'
    | '/admissions/portal'
    | '/admissions/process'
    | '/admissions/registration'
    | '/admissions/report'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/fms/bank'
    | '/fms/cancelled-fee-list'
    | '/fms/change-student-fee'
    | '/fms/cheque-clearence'
    | '/fms/daily-mop-report'
    | '/fms/day-book-report'
    | '/fms/fee-concession-report'
    | '/fms/fee-description'
    | '/fms/fee-description-pending-report'
    | '/fms/fee-due-list-pending-report'
    | '/fms/fee-master'
    | '/fms/fee-pending-report'
    | '/fms/fee-print-list'
    | '/fms/fee-receipt'
    | '/fms/fee-type-master'
    | '/fms/mop-report'
    | '/fms/pickup-point'
    | '/fms/rte-report'
    | '/fms/student-concession'
    | '/fms/transport-fee-due-list-pending-report'
    | '/fms/update-material-fee'
    | '/fms/update-student-fee'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
    | '/admissions/registration/$studentId'
    | '/admissions/registration/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/class-allocation-report'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/feedback-report'
    | '/academic/marks-card'
    | '/academic/marks-report'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/sms-report'
    | '/academic/student-tc'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/summatative-report'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/academic/withheld-list'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/admitted'
    | '/admissions/applications'
    | '/admissions/applied'
    | '/admissions/enquiries'
    | '/admissions/portal'
    | '/admissions/process'
    | '/admissions/registration'
    | '/admissions/report'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/fms/bank'
    | '/fms/cancelled-fee-list'
    | '/fms/change-student-fee'
    | '/fms/cheque-clearence'
    | '/fms/daily-mop-report'
    | '/fms/day-book-report'
    | '/fms/fee-concession-report'
    | '/fms/fee-description'
    | '/fms/fee-description-pending-report'
    | '/fms/fee-due-list-pending-report'
    | '/fms/fee-master'
    | '/fms/fee-pending-report'
    | '/fms/fee-print-list'
    | '/fms/fee-receipt'
    | '/fms/fee-type-master'
    | '/fms/mop-report'
    | '/fms/pickup-point'
    | '/fms/rte-report'
    | '/fms/student-concession'
    | '/fms/transport-fee-due-list-pending-report'
    | '/fms/update-material-fee'
    | '/fms/update-student-fee'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
    | '/admissions/registration/$studentId'
    | '/admissions/registration/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/academic/attendance'
    | '/academic/class-allocation-report'
    | '/academic/classes'
    | '/academic/examinations'
    | '/academic/feedback-report'
    | '/academic/marks-card'
    | '/academic/marks-report'
    | '/academic/report-cards'
    | '/academic/results'
    | '/academic/sections'
    | '/academic/sms-report'
    | '/academic/student-tc'
    | '/academic/students'
    | '/academic/subjects'
    | '/academic/summatative-report'
    | '/academic/teachers'
    | '/academic/timetable'
    | '/academic/withheld-list'
    | '/administration/communication'
    | '/administration/documents'
    | '/administration/events'
    | '/administration/inventory'
    | '/administration/library'
    | '/administration/transport'
    | '/admissions/admitted'
    | '/admissions/applications'
    | '/admissions/applied'
    | '/admissions/enquiries'
    | '/admissions/portal'
    | '/admissions/process'
    | '/admissions/registration'
    | '/admissions/report'
    | '/finance/expenses'
    | '/finance/fee-structure'
    | '/finance/fees'
    | '/finance/payments'
    | '/finance/reports'
    | '/fms/bank'
    | '/fms/cancelled-fee-list'
    | '/fms/change-student-fee'
    | '/fms/cheque-clearence'
    | '/fms/daily-mop-report'
    | '/fms/day-book-report'
    | '/fms/fee-concession-report'
    | '/fms/fee-description'
    | '/fms/fee-description-pending-report'
    | '/fms/fee-due-list-pending-report'
    | '/fms/fee-master'
    | '/fms/fee-pending-report'
    | '/fms/fee-print-list'
    | '/fms/fee-receipt'
    | '/fms/fee-type-master'
    | '/fms/mop-report'
    | '/fms/pickup-point'
    | '/fms/rte-report'
    | '/fms/student-concession'
    | '/fms/transport-fee-due-list-pending-report'
    | '/fms/update-material-fee'
    | '/fms/update-student-fee'
    | '/hr/leave-management'
    | '/hr/payroll'
    | '/hr/staff'
    | '/learning/assignments'
    | '/learning/courses'
    | '/learning/lessons'
    | '/learning/online-classes'
    | '/reports/academic'
    | '/reports/attendance'
    | '/reports/fees'
    | '/reports/students'
    | '/admissions/registration/$studentId'
    | '/admissions/registration/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  AcademicAttendanceRoute: typeof AcademicAttendanceRoute
  AcademicClassAllocationReportRoute: typeof AcademicClassAllocationReportRoute
  AcademicClassesRoute: typeof AcademicClassesRoute
  AcademicExaminationsRoute: typeof AcademicExaminationsRoute
  AcademicFeedbackReportRoute: typeof AcademicFeedbackReportRoute
  AcademicMarksCardRoute: typeof AcademicMarksCardRoute
  AcademicMarksReportRoute: typeof AcademicMarksReportRoute
  AcademicReportCardsRoute: typeof AcademicReportCardsRoute
  AcademicResultsRoute: typeof AcademicResultsRoute
  AcademicSectionsRoute: typeof AcademicSectionsRoute
  AcademicSmsReportRoute: typeof AcademicSmsReportRoute
  AcademicStudentTcRoute: typeof AcademicStudentTcRoute
  AcademicStudentsRoute: typeof AcademicStudentsRoute
  AcademicSubjectsRoute: typeof AcademicSubjectsRoute
  AcademicSummatativeReportRoute: typeof AcademicSummatativeReportRoute
  AcademicTeachersRoute: typeof AcademicTeachersRoute
  AcademicTimetableRoute: typeof AcademicTimetableRoute
  AcademicWithheldListRoute: typeof AcademicWithheldListRoute
  AdministrationCommunicationRoute: typeof AdministrationCommunicationRoute
  AdministrationDocumentsRoute: typeof AdministrationDocumentsRoute
  AdministrationEventsRoute: typeof AdministrationEventsRoute
  AdministrationInventoryRoute: typeof AdministrationInventoryRoute
  AdministrationLibraryRoute: typeof AdministrationLibraryRoute
  AdministrationTransportRoute: typeof AdministrationTransportRoute
  AdmissionsAdmittedRoute: typeof AdmissionsAdmittedRoute
  AdmissionsApplicationsRoute: typeof AdmissionsApplicationsRoute
  AdmissionsAppliedRoute: typeof AdmissionsAppliedRoute
  AdmissionsEnquiriesRoute: typeof AdmissionsEnquiriesRoute
  AdmissionsPortalRoute: typeof AdmissionsPortalRoute
  AdmissionsProcessRoute: typeof AdmissionsProcessRoute
  AdmissionsRegistrationRoute: typeof AdmissionsRegistrationRouteWithChildren
  AdmissionsReportRoute: typeof AdmissionsReportRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceFeeStructureRoute: typeof FinanceFeeStructureRoute
  FinanceFeesRoute: typeof FinanceFeesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FmsBankRoute: typeof FmsBankRoute
  FmsCancelledFeeListRoute: typeof FmsCancelledFeeListRoute
  FmsChangeStudentFeeRoute: typeof FmsChangeStudentFeeRoute
  FmsChequeClearenceRoute: typeof FmsChequeClearenceRoute
  FmsDailyMopReportRoute: typeof FmsDailyMopReportRoute
  FmsDayBookReportRoute: typeof FmsDayBookReportRoute
  FmsFeeConcessionReportRoute: typeof FmsFeeConcessionReportRoute
  FmsFeeDescriptionRoute: typeof FmsFeeDescriptionRoute
  FmsFeeDescriptionPendingReportRoute: typeof FmsFeeDescriptionPendingReportRoute
  FmsFeeDueListPendingReportRoute: typeof FmsFeeDueListPendingReportRoute
  FmsFeeMasterRoute: typeof FmsFeeMasterRoute
  FmsFeePendingReportRoute: typeof FmsFeePendingReportRoute
  FmsFeePrintListRoute: typeof FmsFeePrintListRoute
  FmsFeeReceiptRoute: typeof FmsFeeReceiptRoute
  FmsFeeTypeMasterRoute: typeof FmsFeeTypeMasterRoute
  FmsMopReportRoute: typeof FmsMopReportRoute
  FmsPickupPointRoute: typeof FmsPickupPointRoute
  FmsRteReportRoute: typeof FmsRteReportRoute
  FmsStudentConcessionRoute: typeof FmsStudentConcessionRoute
  FmsTransportFeeDueListPendingReportRoute: typeof FmsTransportFeeDueListPendingReportRoute
  FmsUpdateMaterialFeeRoute: typeof FmsUpdateMaterialFeeRoute
  FmsUpdateStudentFeeRoute: typeof FmsUpdateStudentFeeRoute
  HrLeaveManagementRoute: typeof HrLeaveManagementRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrStaffRoute: typeof HrStaffRoute
  LearningAssignmentsRoute: typeof LearningAssignmentsRoute
  LearningCoursesRoute: typeof LearningCoursesRoute
  LearningLessonsRoute: typeof LearningLessonsRoute
  LearningOnlineClassesRoute: typeof LearningOnlineClassesRoute
  ReportsAcademicRoute: typeof ReportsAcademicRoute
  ReportsAttendanceRoute: typeof ReportsAttendanceRoute
  ReportsFeesRoute: typeof ReportsFeesRoute
  ReportsStudentsRoute: typeof ReportsStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/attendance': {
      id: '/academic/attendance'
      path: '/academic/attendance'
      fullPath: '/academic/attendance'
      preLoaderRoute: typeof AcademicAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/class-allocation-report': {
      id: '/academic/class-allocation-report'
      path: '/academic/class-allocation-report'
      fullPath: '/academic/class-allocation-report'
      preLoaderRoute: typeof AcademicClassAllocationReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/classes': {
      id: '/academic/classes'
      path: '/academic/classes'
      fullPath: '/academic/classes'
      preLoaderRoute: typeof AcademicClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/examinations': {
      id: '/academic/examinations'
      path: '/academic/examinations'
      fullPath: '/academic/examinations'
      preLoaderRoute: typeof AcademicExaminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/feedback-report': {
      id: '/academic/feedback-report'
      path: '/academic/feedback-report'
      fullPath: '/academic/feedback-report'
      preLoaderRoute: typeof AcademicFeedbackReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/marks-card': {
      id: '/academic/marks-card'
      path: '/academic/marks-card'
      fullPath: '/academic/marks-card'
      preLoaderRoute: typeof AcademicMarksCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/marks-report': {
      id: '/academic/marks-report'
      path: '/academic/marks-report'
      fullPath: '/academic/marks-report'
      preLoaderRoute: typeof AcademicMarksReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/report-cards': {
      id: '/academic/report-cards'
      path: '/academic/report-cards'
      fullPath: '/academic/report-cards'
      preLoaderRoute: typeof AcademicReportCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/results': {
      id: '/academic/results'
      path: '/academic/results'
      fullPath: '/academic/results'
      preLoaderRoute: typeof AcademicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/sections': {
      id: '/academic/sections'
      path: '/academic/sections'
      fullPath: '/academic/sections'
      preLoaderRoute: typeof AcademicSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/sms-report': {
      id: '/academic/sms-report'
      path: '/academic/sms-report'
      fullPath: '/academic/sms-report'
      preLoaderRoute: typeof AcademicSmsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/student-tc': {
      id: '/academic/student-tc'
      path: '/academic/student-tc'
      fullPath: '/academic/student-tc'
      preLoaderRoute: typeof AcademicStudentTcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/students': {
      id: '/academic/students'
      path: '/academic/students'
      fullPath: '/academic/students'
      preLoaderRoute: typeof AcademicStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/subjects': {
      id: '/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AcademicSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/summatative-report': {
      id: '/academic/summatative-report'
      path: '/academic/summatative-report'
      fullPath: '/academic/summatative-report'
      preLoaderRoute: typeof AcademicSummatativeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/teachers': {
      id: '/academic/teachers'
      path: '/academic/teachers'
      fullPath: '/academic/teachers'
      preLoaderRoute: typeof AcademicTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/timetable': {
      id: '/academic/timetable'
      path: '/academic/timetable'
      fullPath: '/academic/timetable'
      preLoaderRoute: typeof AcademicTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/withheld-list': {
      id: '/academic/withheld-list'
      path: '/academic/withheld-list'
      fullPath: '/academic/withheld-list'
      preLoaderRoute: typeof AcademicWithheldListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/communication': {
      id: '/administration/communication'
      path: '/administration/communication'
      fullPath: '/administration/communication'
      preLoaderRoute: typeof AdministrationCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/documents': {
      id: '/administration/documents'
      path: '/administration/documents'
      fullPath: '/administration/documents'
      preLoaderRoute: typeof AdministrationDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/events': {
      id: '/administration/events'
      path: '/administration/events'
      fullPath: '/administration/events'
      preLoaderRoute: typeof AdministrationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/inventory': {
      id: '/administration/inventory'
      path: '/administration/inventory'
      fullPath: '/administration/inventory'
      preLoaderRoute: typeof AdministrationInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/library': {
      id: '/administration/library'
      path: '/administration/library'
      fullPath: '/administration/library'
      preLoaderRoute: typeof AdministrationLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/transport': {
      id: '/administration/transport'
      path: '/administration/transport'
      fullPath: '/administration/transport'
      preLoaderRoute: typeof AdministrationTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/admitted': {
      id: '/admissions/admitted'
      path: '/admissions/admitted'
      fullPath: '/admissions/admitted'
      preLoaderRoute: typeof AdmissionsAdmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applications': {
      id: '/admissions/applications'
      path: '/admissions/applications'
      fullPath: '/admissions/applications'
      preLoaderRoute: typeof AdmissionsApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/applied': {
      id: '/admissions/applied'
      path: '/admissions/applied'
      fullPath: '/admissions/applied'
      preLoaderRoute: typeof AdmissionsAppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/enquiries': {
      id: '/admissions/enquiries'
      path: '/admissions/enquiries'
      fullPath: '/admissions/enquiries'
      preLoaderRoute: typeof AdmissionsEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/portal': {
      id: '/admissions/portal'
      path: '/admissions/portal'
      fullPath: '/admissions/portal'
      preLoaderRoute: typeof AdmissionsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/process': {
      id: '/admissions/process'
      path: '/admissions/process'
      fullPath: '/admissions/process'
      preLoaderRoute: typeof AdmissionsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/registration': {
      id: '/admissions/registration'
      path: '/admissions/registration'
      fullPath: '/admissions/registration'
      preLoaderRoute: typeof AdmissionsRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/report': {
      id: '/admissions/report'
      path: '/admissions/report'
      fullPath: '/admissions/report'
      preLoaderRoute: typeof AdmissionsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fee-structure': {
      id: '/finance/fee-structure'
      path: '/finance/fee-structure'
      fullPath: '/finance/fee-structure'
      preLoaderRoute: typeof FinanceFeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fees': {
      id: '/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof FinanceFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/bank': {
      id: '/fms/bank'
      path: '/fms/bank'
      fullPath: '/fms/bank'
      preLoaderRoute: typeof FmsBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/cancelled-fee-list': {
      id: '/fms/cancelled-fee-list'
      path: '/fms/cancelled-fee-list'
      fullPath: '/fms/cancelled-fee-list'
      preLoaderRoute: typeof FmsCancelledFeeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/change-student-fee': {
      id: '/fms/change-student-fee'
      path: '/fms/change-student-fee'
      fullPath: '/fms/change-student-fee'
      preLoaderRoute: typeof FmsChangeStudentFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/cheque-clearence': {
      id: '/fms/cheque-clearence'
      path: '/fms/cheque-clearence'
      fullPath: '/fms/cheque-clearence'
      preLoaderRoute: typeof FmsChequeClearenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/daily-mop-report': {
      id: '/fms/daily-mop-report'
      path: '/fms/daily-mop-report'
      fullPath: '/fms/daily-mop-report'
      preLoaderRoute: typeof FmsDailyMopReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/day-book-report': {
      id: '/fms/day-book-report'
      path: '/fms/day-book-report'
      fullPath: '/fms/day-book-report'
      preLoaderRoute: typeof FmsDayBookReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-concession-report': {
      id: '/fms/fee-concession-report'
      path: '/fms/fee-concession-report'
      fullPath: '/fms/fee-concession-report'
      preLoaderRoute: typeof FmsFeeConcessionReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-description': {
      id: '/fms/fee-description'
      path: '/fms/fee-description'
      fullPath: '/fms/fee-description'
      preLoaderRoute: typeof FmsFeeDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-description-pending-report': {
      id: '/fms/fee-description-pending-report'
      path: '/fms/fee-description-pending-report'
      fullPath: '/fms/fee-description-pending-report'
      preLoaderRoute: typeof FmsFeeDescriptionPendingReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-due-list-pending-report': {
      id: '/fms/fee-due-list-pending-report'
      path: '/fms/fee-due-list-pending-report'
      fullPath: '/fms/fee-due-list-pending-report'
      preLoaderRoute: typeof FmsFeeDueListPendingReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-master': {
      id: '/fms/fee-master'
      path: '/fms/fee-master'
      fullPath: '/fms/fee-master'
      preLoaderRoute: typeof FmsFeeMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-pending-report': {
      id: '/fms/fee-pending-report'
      path: '/fms/fee-pending-report'
      fullPath: '/fms/fee-pending-report'
      preLoaderRoute: typeof FmsFeePendingReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-print-list': {
      id: '/fms/fee-print-list'
      path: '/fms/fee-print-list'
      fullPath: '/fms/fee-print-list'
      preLoaderRoute: typeof FmsFeePrintListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-receipt': {
      id: '/fms/fee-receipt'
      path: '/fms/fee-receipt'
      fullPath: '/fms/fee-receipt'
      preLoaderRoute: typeof FmsFeeReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/fee-type-master': {
      id: '/fms/fee-type-master'
      path: '/fms/fee-type-master'
      fullPath: '/fms/fee-type-master'
      preLoaderRoute: typeof FmsFeeTypeMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/mop-report': {
      id: '/fms/mop-report'
      path: '/fms/mop-report'
      fullPath: '/fms/mop-report'
      preLoaderRoute: typeof FmsMopReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/pickup-point': {
      id: '/fms/pickup-point'
      path: '/fms/pickup-point'
      fullPath: '/fms/pickup-point'
      preLoaderRoute: typeof FmsPickupPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/rte-report': {
      id: '/fms/rte-report'
      path: '/fms/rte-report'
      fullPath: '/fms/rte-report'
      preLoaderRoute: typeof FmsRteReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/student-concession': {
      id: '/fms/student-concession'
      path: '/fms/student-concession'
      fullPath: '/fms/student-concession'
      preLoaderRoute: typeof FmsStudentConcessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/transport-fee-due-list-pending-report': {
      id: '/fms/transport-fee-due-list-pending-report'
      path: '/fms/transport-fee-due-list-pending-report'
      fullPath: '/fms/transport-fee-due-list-pending-report'
      preLoaderRoute: typeof FmsTransportFeeDueListPendingReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/update-material-fee': {
      id: '/fms/update-material-fee'
      path: '/fms/update-material-fee'
      fullPath: '/fms/update-material-fee'
      preLoaderRoute: typeof FmsUpdateMaterialFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fms/update-student-fee': {
      id: '/fms/update-student-fee'
      path: '/fms/update-student-fee'
      fullPath: '/fms/update-student-fee'
      preLoaderRoute: typeof FmsUpdateStudentFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave-management': {
      id: '/hr/leave-management'
      path: '/hr/leave-management'
      fullPath: '/hr/leave-management'
      preLoaderRoute: typeof HrLeaveManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/staff': {
      id: '/hr/staff'
      path: '/hr/staff'
      fullPath: '/hr/staff'
      preLoaderRoute: typeof HrStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/assignments': {
      id: '/learning/assignments'
      path: '/learning/assignments'
      fullPath: '/learning/assignments'
      preLoaderRoute: typeof LearningAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/courses': {
      id: '/learning/courses'
      path: '/learning/courses'
      fullPath: '/learning/courses'
      preLoaderRoute: typeof LearningCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/lessons': {
      id: '/learning/lessons'
      path: '/learning/lessons'
      fullPath: '/learning/lessons'
      preLoaderRoute: typeof LearningLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/online-classes': {
      id: '/learning/online-classes'
      path: '/learning/online-classes'
      fullPath: '/learning/online-classes'
      preLoaderRoute: typeof LearningOnlineClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/academic': {
      id: '/reports/academic'
      path: '/reports/academic'
      fullPath: '/reports/academic'
      preLoaderRoute: typeof ReportsAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/attendance': {
      id: '/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof ReportsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/fees': {
      id: '/reports/fees'
      path: '/reports/fees'
      fullPath: '/reports/fees'
      preLoaderRoute: typeof ReportsFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/students': {
      id: '/reports/students'
      path: '/reports/students'
      fullPath: '/reports/students'
      preLoaderRoute: typeof ReportsStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/registration/$studentId': {
      id: '/admissions/registration/$studentId'
      path: '/$studentId'
      fullPath: '/admissions/registration/$studentId'
      preLoaderRoute: typeof AdmissionsRegistrationStudentIdRouteImport
      parentRoute: typeof AdmissionsRegistrationRoute
    }
    '/admissions/registration/new': {
      id: '/admissions/registration/new'
      path: '/new'
      fullPath: '/admissions/registration/new'
      preLoaderRoute: typeof AdmissionsRegistrationNewRouteImport
      parentRoute: typeof AdmissionsRegistrationRoute
    }
  }
}

interface AdmissionsRegistrationRouteChildren {
  AdmissionsRegistrationStudentIdRoute: typeof AdmissionsRegistrationStudentIdRoute
  AdmissionsRegistrationNewRoute: typeof AdmissionsRegistrationNewRoute
}

const AdmissionsRegistrationRouteChildren: AdmissionsRegistrationRouteChildren =
  {
    AdmissionsRegistrationStudentIdRoute: AdmissionsRegistrationStudentIdRoute,
    AdmissionsRegistrationNewRoute: AdmissionsRegistrationNewRoute,
  }

const AdmissionsRegistrationRouteWithChildren =
  AdmissionsRegistrationRoute._addFileChildren(
    AdmissionsRegistrationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  AcademicAttendanceRoute: AcademicAttendanceRoute,
  AcademicClassAllocationReportRoute: AcademicClassAllocationReportRoute,
  AcademicClassesRoute: AcademicClassesRoute,
  AcademicExaminationsRoute: AcademicExaminationsRoute,
  AcademicFeedbackReportRoute: AcademicFeedbackReportRoute,
  AcademicMarksCardRoute: AcademicMarksCardRoute,
  AcademicMarksReportRoute: AcademicMarksReportRoute,
  AcademicReportCardsRoute: AcademicReportCardsRoute,
  AcademicResultsRoute: AcademicResultsRoute,
  AcademicSectionsRoute: AcademicSectionsRoute,
  AcademicSmsReportRoute: AcademicSmsReportRoute,
  AcademicStudentTcRoute: AcademicStudentTcRoute,
  AcademicStudentsRoute: AcademicStudentsRoute,
  AcademicSubjectsRoute: AcademicSubjectsRoute,
  AcademicSummatativeReportRoute: AcademicSummatativeReportRoute,
  AcademicTeachersRoute: AcademicTeachersRoute,
  AcademicTimetableRoute: AcademicTimetableRoute,
  AcademicWithheldListRoute: AcademicWithheldListRoute,
  AdministrationCommunicationRoute: AdministrationCommunicationRoute,
  AdministrationDocumentsRoute: AdministrationDocumentsRoute,
  AdministrationEventsRoute: AdministrationEventsRoute,
  AdministrationInventoryRoute: AdministrationInventoryRoute,
  AdministrationLibraryRoute: AdministrationLibraryRoute,
  AdministrationTransportRoute: AdministrationTransportRoute,
  AdmissionsAdmittedRoute: AdmissionsAdmittedRoute,
  AdmissionsApplicationsRoute: AdmissionsApplicationsRoute,
  AdmissionsAppliedRoute: AdmissionsAppliedRoute,
  AdmissionsEnquiriesRoute: AdmissionsEnquiriesRoute,
  AdmissionsPortalRoute: AdmissionsPortalRoute,
  AdmissionsProcessRoute: AdmissionsProcessRoute,
  AdmissionsRegistrationRoute: AdmissionsRegistrationRouteWithChildren,
  AdmissionsReportRoute: AdmissionsReportRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceFeeStructureRoute: FinanceFeeStructureRoute,
  FinanceFeesRoute: FinanceFeesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FmsBankRoute: FmsBankRoute,
  FmsCancelledFeeListRoute: FmsCancelledFeeListRoute,
  FmsChangeStudentFeeRoute: FmsChangeStudentFeeRoute,
  FmsChequeClearenceRoute: FmsChequeClearenceRoute,
  FmsDailyMopReportRoute: FmsDailyMopReportRoute,
  FmsDayBookReportRoute: FmsDayBookReportRoute,
  FmsFeeConcessionReportRoute: FmsFeeConcessionReportRoute,
  FmsFeeDescriptionRoute: FmsFeeDescriptionRoute,
  FmsFeeDescriptionPendingReportRoute: FmsFeeDescriptionPendingReportRoute,
  FmsFeeDueListPendingReportRoute: FmsFeeDueListPendingReportRoute,
  FmsFeeMasterRoute: FmsFeeMasterRoute,
  FmsFeePendingReportRoute: FmsFeePendingReportRoute,
  FmsFeePrintListRoute: FmsFeePrintListRoute,
  FmsFeeReceiptRoute: FmsFeeReceiptRoute,
  FmsFeeTypeMasterRoute: FmsFeeTypeMasterRoute,
  FmsMopReportRoute: FmsMopReportRoute,
  FmsPickupPointRoute: FmsPickupPointRoute,
  FmsRteReportRoute: FmsRteReportRoute,
  FmsStudentConcessionRoute: FmsStudentConcessionRoute,
  FmsTransportFeeDueListPendingReportRoute:
    FmsTransportFeeDueListPendingReportRoute,
  FmsUpdateMaterialFeeRoute: FmsUpdateMaterialFeeRoute,
  FmsUpdateStudentFeeRoute: FmsUpdateStudentFeeRoute,
  HrLeaveManagementRoute: HrLeaveManagementRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrStaffRoute: HrStaffRoute,
  LearningAssignmentsRoute: LearningAssignmentsRoute,
  LearningCoursesRoute: LearningCoursesRoute,
  LearningLessonsRoute: LearningLessonsRoute,
  LearningOnlineClassesRoute: LearningOnlineClassesRoute,
  ReportsAcademicRoute: ReportsAcademicRoute,
  ReportsAttendanceRoute: ReportsAttendanceRoute,
  ReportsFeesRoute: ReportsFeesRoute,
  ReportsStudentsRoute: ReportsStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
